name: Build and Release  

on:  
  push:  
    tags:  
      - 'v*.*.*'  
  workflow_dispatch:  

jobs:  
  build-and-release:  
    runs-on: ubuntu-latest  

    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest]  
        arch: [x86, x64]  

    steps:  
    - name: Check out Git repository  
      uses: actions/checkout@v3  

    - name: Set up the build environment  
      run: |  
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then  
          sudo apt-get update  
          sudo apt-get install -y build-essential  
          if [ "${{ matrix.arch }}" == "x86" ]; then  
            sudo apt-get install -y gcc-multilib  
            export CFLAGS=-m32  
            export LDFLAGS=-m32  
          fi  
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then  
          choco install mingw  
          if [ "${{ matrix.arch }}" == "x86" ]; then  
            echo "Setting up Windows x86 environment"  
          fi  
        fi  
      shell: bash  

    - name: Build project  
      run: |  
        ./autogen.sh  
        ./configure  
        make  

    - name: Upload Release Assets  
      uses: actions/upload-artifact@v3  
      with:  
        name: nbtscan-${{ matrix.os }}-${{ matrix.arch }}  
        path: release/${{ matrix.os }}-${{ matrix.arch }}
